### ISSUE TITLE
Unable to install unfree software

### ISSUE THREAD

**Issue by jerivl** [ne9z/dotfiles-flake#4]
## Expected Behavior
The following solutions are suggested by NixOS for installing unfree software. I was expecting that one options would allow me to install the `zerotierone` package. 
```
[root@ssd:/etc/nixos]# nixos-rebuild switch
building the system configuration...
error: Package ‘zerotierone-1.10.6’ in /nix/store/mz6lqpbsp4h36kgahvwfrgdjzz042hpn-source/pkgs/tools/networking/zerotierone/default.nix:95 has an unfree license (‘bsl11’), refusing to evaluate.

       a) To temporarily allow unfree packages, you can use an environment variable
          for a single invocation of the nix tools.

            $ export NIXPKGS_ALLOW_UNFREE=1

        Note: For `nix shell`, `nix build`, `nix develop` or any other Nix 2.4+
        (Flake) command, `--impure` must be passed in order to read this
        environment variable.

       b) For `nixos-rebuild` you can set
         { nixpkgs.config.allowUnfree = true; }
       in configuration.nix to override this.

       Alternatively you can configure a predicate to allow specific packages:
         { nixpkgs.config.allowUnfreePredicate = pkg: builtins.elem (lib.getName pkg) [
             "zerotierone"
           ];
         }

       c) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
         { allowUnfree = true; }
       to ~/.config/nixpkgs/config.nix.
(use '--show-trace' to show detailed location information)

```

## Current Behavior
I have tried solutions a/b to no success. Nix still refuses to install unfree packages.

## Context (Environment)
Fresh NixOS baremetal installation following the [OpenZFS guide for ZFS on Root for NixOS](https://openzfs.github.io/openzfs-docs/Getting%20Started/NixOS/Root%20on%20ZFS.html)

The repo for my configs are [here](https://github.com/jerivl/dotfiles). The commits may be a bit messy as this is one of my first experiments using nix.

**Comment by ne9z** [comment]
I'm a proud [Stallmanite](https://www.urbandictionary.com/define.php?term=stallmanite) so I would not enable this option by default in the template repo.  (I use GitHub with JavaScript disabled.)

However one should have the freedom to decide for oneself.  Because this is a flake, Option A will not work.  Because you are using nixos-switch, Option C will not work either.

I tried both methods in Option B and both of them work.  As described, you can either enable all freedom-robbing program by editing `configuration.nix` and add this line below system.stateVersion line
```
nixpkgs.config.allowUnfree = true;
```
or you can only enable one specific freedom-robbing program by setting
```
nixpkgs.config.allowUnfreePredicate = pkg: builtins.elem (lib.getName pkg) [
             "zerotierone"
           ];
```
also below `system.stateVersion` line.  Then append the package name to the list of system packages, which is `environment.systemPackages` variable.

**Comment by jerivl** [comment]
Found a solution, but there seems to be issues with the current stable branch of `nixpkgs.legacyPackages.${system}` for 23.05 which was preventing me from installing unfree software which would ignore the `NIXPKGS_ALLOW_UNFREE` flag and the `nixpkgs.config.allowUnfree = true;` line in configuration.nix

The way I fixed this was to make the following edits to:
### flake.nix
```diff
-- > pkgs = nixpkgs.legacyPackages.${system};
++ > pkgs = import nixpkgs {
++ >          config = { allowUnfree = true; };
++ >          inherit system;
++ >        };
```
### configuration.nix
```diff
   > system.stateVersion = "23.05";
++ > nixpkgs.config.allowUnfree = true;
```
